#!/bin/sh

# start daemon key mapper
sxhkd &

# start panel
$HOME/.config/bspwm/panel &

# bspc config
bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# bspc rules
bspc rule -a Chromium desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Steam desktop='^10'

# bspc monitors
bspc monitor -d dev www chat art misc 6 7 8 9 game

# xfonts
TEWI_FONT=$HOME/fonts/tewi/out
if [ -d $TEWI_FONT ]; then
  xset +fp $TEWI_FONT
fi

# touchpad
xinput disable 13

# autostart
autostart() {
  if [ ! $(pidof -x $1 >/dev/null) ]; then
    $1
  fi
}
autostart google-chrome-stable &
autostart discord-canary &
if [ ! $(pidof -x steam >/dev/null) ]; then
  STEAM_RUNTIME=0 steam &
fi
