#!/bin/sh

if [[ "$(amixer | grep off)" ]]; then
  echo mute
  echo mute
  echo '#ff5a52'
else
  perc=$(amixer get Master | grep -i 'front left:' | cut -d'[' -f2 | cut -d']' -f1)
  echo $perc
  echo $perc
fi
