#!/bin/bash

# this font overrides all weights of the current font being
# used to another font.
#
# you should only use this function with a bitmap font, hence
# the `bit_' prefix.
bit_changefont () {
  echo -e -n "\033]710;$1\033\\"
  # bold
  echo -e -n "\033]711;$1\033\\"
  # italic
  echo -e -n "\033]712;$1\033\\"
  # bold/italic
  echo -e -n "\033]713;$1\033\\"
}

# only changes the bold weight of the current font being used.
#
# this is exclusively for tewi.
bit_changebold () {
  echo -e -n "\033]711;$1\033\\"
}

# font definitions
ibm_bios="xft:PxPlus IBM BIOS:pixelsize=8:antialias=false"
ibm_ega8="xft:PxPlus IBM EGA8:pixelsize=15:antialias=false"
ibm_vga8="xft:PxPlus IBM VGA8:pixelsize=15:antialias=false"
tewi="-lucy-tewi-medium-r-normal--11-90-*-*-c-60-iso10646-*"
tewi_bold="-lucy-tewi-bold-r-normal--11-80-*-*-c-60-iso10646-*"

if [ "$1" == "bit_med" ]; then
  bit_changefont "$ibm_ega8"
elif [ "$1" == "bit_big" ]; then
  bit_changefont "$ibm_vga8"
elif [ "$1" == "bit_tiny" ]; then
  bit_changefont "$ibm_bios"
elif [ "$1" == "tewi" ]; then
  bit_changefont "$tewi"
  bit_changebold "$tewi_bold"
elif [ "$1" == "custom" ]; then
  echo -e "\033]710;$2\033\\"
fi
