#!/usr/bin/env ruby

editor_program = 'nvim'

if Dir.exists?(ARGV[0] || '')
  # we have been pointed to a directory
  system("pushd #{ARGV[0]}; #{editor_program}")
else
  system("#{editor_program} #{ARGV.join(' ')}")
end

