#!/bin/bash

# start daemon key mapper
sxhkd &

# bspc config
bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# bspc rules
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^3'

# bspc monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# xfonts
TEWI_FONT=$HOME/fonts/tewi/out
[[ -d $TEWI_FONT ]] && xset +fp $TEWI_FONT

# touchpad
xinput disable 13
