#!/bin/sh

. ~/.config/bspwm/panel_colors
. ~/.config/bspwm/panel_config
  
dmenu_run -z -h $PANEL_HEIGHT -p run -fn "-lucy-tewi-medium-*" -nf "$COLOR_DEFAULT_FG" \
  -nb "$COLOR_DEFAULT_BG" -sf "$COLOR_FOCUSED_OCCUPIED_FG" \
  -sb "$COLOR_FOCUSED_OCCUPIED_BG" 
