colorscheme zenburn

set-option global indentwidth 2
set-option global scrolloff 5,0

add-highlighter global/ number-lines

# soft tabs (insertion)
hook global InsertChar \t %{ try %{
    execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}

# soft tabs (deletion)
hook global InsertDelete ' ' %{ try %{
    execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}
