# ~/.zshrc

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt extended_history
setopt inc_append_history
setopt share_history
setopt hist_reduce_blanks
setopt correct
setopt prompt_subst

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[1;9C" forward-word
bindkey "^[[1;9D" backward-word

autoload -U compinit && compinit
autoload -U vcs_info
zstyle ':completion:*' menu select
zstyle ':completion:::::' completer _complete _approximate
zstyle ':completion:*:approximate:*' max-errors 3

PURE_PROMPT_SYMBOL='🡂'

# --- zplug
source ~/.zplug/init.zsh

zplug "mafredri/zsh-async", from:github
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme

if ! zplug check; then
  printf "hi! install missing zplug plugins? [y/N]: "
  if read -q; then
    echo
    zplug install
  fi
fi
zplug load

export FZF_DEFAULT_OPTS='--color=16'
export MAGICK_HOME='/usr/local/opt/imagemagick@6/'
export EDITOR='nvim'
export GOPATH="$HOME/src/go"

# zsh-completions
[ -d /usr/local/share/zsh-completions ] && fpath=(/usr/local/share/zsh-completions $fpath)

typeset -U path # enforce uniqueness
path=(
  # langs
  ~/Library/Haskell/bin
  ~/.npm/bin
  ~/.yarn/bin
  $GOPATH/bin
  $HOME/.local/bin
  $HOME/Code/dotfiles/bin
  /usr/local/bin
  $path
)

[ -x "/usr/local/bin/hub" ] && alias git='hub'

alias dk='docker'
alias dkc='docker-compose'
alias br='brew'
alias gi='git init'
alias grb='git rebase'
alias gc='git commit -v'
alias gco='git checkout'
alias gr='git remote'
alias gd='git diff'
alias gds='git diff --staged'
alias gt='git tag'
alias gst='git status -s'
alias gp='git push'
alias gpl='git pull'
alias grh='git reset HEAD'
alias gs='git show'
alias gsh='git stash'
alias gl="git log --graph"
alias grm='git rm'
alias gb='git branch'
alias ga='git add'
alias gap='git add -p'
alias gcl='git clone'
alias e="$EDITOR"
alias ls='ls -GFh'
alias ll='ls -l'
alias la='ls -al'
alias reload='source ~/.zshrc'
alias usage='du -h -d 1 .'
alias ydl='youtube-dl'
alias ydle='ydl --extract-audio --audio-format mp3'
alias md='mkdir'
alias sc='sudo systemctl'
alias se="sudo -E $EDITOR"
alias irb='irb --simple-prompt'
alias ipy='ipython'
alias py='python3'
if type kitty &> /dev/null; then
  alias ssh='kitty +kitten ssh'
fi
alias s='sudo salt'
alias sa="sudo salt '*'"

gsu() {
  [ ! -n "$1" ] && return
  git remote add origin "$1"
  git push -u origin master
}

# quickly move file to current directory, and create link from file
# in current dir to previous location
lqk() {
  if [ -n "$2" ]; then
    dest="$2"
  else
    dest=$(basename $1)
  fi
  mv -v "$1" "$dest"
  ln -vs "$(greadlink -f $dest)" "$1"
}

[ -f /usr/local/bin/opam ] && eval $(opam config env)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
