#!/bin/sh

status=$(nmcli -t --fields state -c no g)

if [ "$status" = "connecting" ]; then
  echo connecting
  exit 33
fi

if [ "$status" = "disconnected"] || [ "$status" = "asleep" ]; then
  echo not connected
  exit 33
fi

if [ "$status" = "connected" ]; then
  essid=$(nmcli -t --fields name -c no c show --active)
  echo $essid
  echo $essid
fi
